port: 7880
bind_addresses:
  - ""
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 50100
  use_external_ip: false
redis:
  address: redis:6379
keys:
  devkey: secretdevkey123456789talkive
logging:
  level: info
  pion_level: warn
turn:
  enabled: true
  domain: localhost
  tls_port: 5349
  udp_port: 3478
